### PR TITLE
Complete rewrite of client to full JS SDK, using ES6, with support of all major features in Signal K 1.0

### PR DESCRIPTION
**Pull request by tkurki**
SUPERCEDES #40 

**Main features:**

1. mDNS server discovery
2. Security/authentication (over REST) support
3. Notifications/alarms support
4. Access Request mechanism (responding to devices' access requests)
5. Security/authentication (over WS) support
6. PUT requests via request/response over WS
7. Supports making an Access Request for devices
8. PUT requests via REST

**I believe 1.0 is ready for prime time, as:**

- The code is solid, as it's already been used in production for almost a year (mind, that is an earlier version with less features, but same basic code)
- The current client is hopelessly outdated
- The feature set is much more complete than any other client out there at the time of writing (as far as I know)
- The unit tests are pretty complete

### CODE REVIEW

**Comment by tkurki** [comment]
@fabdrol let's continue here so I can contribute directly instead of just PRing your fork.

The tests are now run against a local SK Node server - but there is a small issue in the server I need to fix, I'll comment here when things work in master or the release version.

*BUT* there seems to be a fundamental problem: if authenticated the contstructor fires off a login request. Any requests done before that login request returns are done without any authentication!

What was your plan with failed logins (invalid password)? Listen for `error` and just create a new Client? As things are pretty Promise based how about `createClient` that returns a Promise of a Client? That way failed logins/connections would be easy and explicit to catch. The Promise would resolve only after login is successful.

**Comment by tkurki** [comment]
https://github.com/SignalK/signalk-server-node/pull/735

**Comment by fabdrol** [comment]
@tkurki thanks, this makes sense. 

> _BUT_ there seems to be a fundamental problem: if authenticated the contstructor fires off a login request. Any requests done before that login request returns are done without any authentication!

Can you expand on this a bit? And shall we put it in an issue as soon as this is merged into master? Current master doesn't even have auth after all. 

> What was your plan with failed logins (invalid password)? Listen for `error` and just create a new Client? As things are pretty Promise based how about `createClient` that returns a Promise of a Client? That way failed logins/connections would be easy and explicit to catch. The Promise would resolve only after login is successful.

Basically, up to the user. I think a promise-returning `createClient` is not a bad idea, but let's put that in a separate issue & PR after merging. 

Is there anything that _really_ needs addressing before merging? Otherwise, let's just do it and create some issues for the outstanding things (and close all outdated issues).

**Comment by tkurki** [comment]
Just recording here what we discussed: I don't want to merge this with functionality that is broken for authenticated requests. Let's try to keep this going so that the issue is resolved.

**Comment by tkurki** [comment]
Running a failing test that demonstrates the problem: `npx mocha --require @babel/register --grep 'Fetches'`.

**Comment by fabdrol** [comment]
@tkurki I added a solution for the authentication request issue (finally had some time). Could you take a look?

**Comment by tkurki** [comment]
64cd86b25b963fb9c9e5818a5aca142672161943 looks pretty confusing to me
- there are now two retry mechanisms: Client.pollRetries and Connection._retries, named in different ways
- why the intermediate call to `poll()`, when all `poll` does is create a Promise that resolves with another call to `API()``

How about adding a Promise-valued property `fetchReady` to client, assigned in constructor and returned by reconnect(), that
- is immediately resolved as `Promise.resolve(true)` if there is no authentication
- if there is authentication it is resolved as `true` when authentication completes, successful or not

No need to poll, since `fetch (path, opts)` returns a Promise, so we can first wait on the `fetchReady` promise and then do the actual `fetch` call that does http.

Hmmm do you get what I mean?

**Comment by fabdrol** [comment]
@tkurki yep, seems like a good idea. It was a bit of a rush job anyway. Thanks for feedback.

**Comment by fabdrol** [comment]
@tkurki reset the last commit and implemented your suggestion in a slightly different form. Making `reconnect()` return a promise that is either true or false or error leads to a snake pit of things needing changing -- or a situation where the method returns an error in cases such as `reconnect = false`. 

The current solution achieves the goal without some ugly polling method (i.e., it doesn't resolve `API()` until a `fetchReady` flag is set to true) - without changing the function signature of `reconnect()`. 

BTW, I noticed you implemented a SK server in the tests itself. For me this causes failed tests fo access requests and notifications. Is that due to this change or did I break something along the way without noticing it?

**Comment by fabdrol** [comment]
ping @tkurki

**Comment by tkurki** [comment]
Well if I roll back history to 409e1799c5c46d0543b7857b121763cdecffd5b4 the ones failing are 
```
1) Signal K SDK
       Notifications
         ... Connects and receives notifications:
     Error: Timeout of 60000ms exceeded
  2) Signal K SDK
       REST API
         ... Fetches "self/communication" successfully:
     Error: Error fetching http://localhost:58682/signalk/v1/api/vessels/self/communication: 401 Unauthorized
```
and after your last commit the failures are
```
  1) Signal K SDK
       On-demand authentication using request/response dynamics
         ... successfully authenticates, and then can access resources via the REST API:
  2) Signal K SDK
       Notifications
         ... Connects and receives notifications:
  3) Signal K SDK
       Connection
         ... Fails to get vessel in case of unauthenticated connection:
```


For example I don't understand what should be sending the notification that is [asserted in the test](https://github.com/SignalK/signalk-js-client/blob/fabdrol-sdk/test/index.js#L511-L536).

You can run individual tests like `npx mocha --require @babel/register --exit --grep 'Notifications' --exit`.

I think it is vastly superior to run an embedded server for tests. Setting up a CI is essential for having tests in shape and I don't think it makes sense to depend on your personal server to be up and have a certain version there. We could run the tests also against Artemis in CI if it were available as a Docker image.

So I think the answer lies in fixing the tests, their interdependencies and what needs to be fixed. I don't think I can spare the effort in the near future, but I can help out here and there.

**Comment by fabdrol** [comment]
Thanks, will have a look. 

> I don't think I can spare the effort in the near future, but I can help out here and there.

That's okay, I know the feeling. Once the tests are fixed and CI is set up, I'll send you a ping for a final look-over so we can merge. I've been using this version on X-Miles on various clients (both React Native and browser), no hick-ups so far.

**Comment by fabdrol** [comment]
@tkurki disabled the notification test for now, as that won't work without plugin with the test server. Please have a look when you have a chance.

**Comment by fabdrol** [comment]
ping @tkurki

**Comment by fabdrol** [comment]
@tkurki let me know if you have anything else to add, otherwise I'll merge and push to npm.

**Pull request merged**
