### PR TITLE
feature: Allows SSL/TLS connection to server with self-signed certificate

### PR DESCRIPTION
**Pull request by cmotelet**
With nodejs `signalk-js-client`, refuses to establish a connection to a server with a self-signed certificate.
I have added an optional parameter `noCheckCert`, if true create the WebSocket with the option `rejectUnauthorized: false`.

### CODE REVIEW

**Comment by tkurki** [comment]
What if we named our option the same as ws? Then somebody debugging this in the future would have a little bit easier time.

**Comment by cmotelet** [comment]
This is what I did in my first version but I found the parameter not very explicit (rejectUnauthorized).
And then setting it to `false` to disable the check seemed even less clear to me.
It's up to you I can leave `rejectUnauthorized` everywhere.

**Comment by sbender9** [comment]
I'd say use `rejectUnauthorized`

**Comment by cmotelet** [comment]
@tkurki  & @sbender9  modified to use `rejectUnauthorized` everywhere

**Comment by cmotelet** [comment]
@fabdrol,
this PR is related to the issue #965 (https://github.com/SignalK/signalk-server-node/issues/965) in signalk-server-node
and the canceled PR#967 (https://github.com/SignalK/signalk-server-node/pull/967)

**Comment by fabdrol** [comment]
This looks fine with me, except the travis build error. Any idea what's going on @cmotelet ?

**Review by fabdrol — APPROVED** [review]

**Comment by fabdrol** [comment]
It's still failing. Not sure why, it fails on mDNS server discovery (there's an error thrown by the SK server) but #66 doesn't fail despite the same error

**Comment by cmotelet** [comment]
Cancel multiple errors with travis-ci

**Pull request closed without merging**
