### PR TITLE
Implement back-off policy, more relevant maxRetries default

### PR DESCRIPTION
**Pull request by fabdrol**
This PR implements a more sensible reconnection policy:

- Default maxRetries is now Infinity
- Progressive back-off and reconnect policy (retries * 250 ms, so 250, 500, etc)
- A back off event
- Unit test

Please comment your thoughts.

### CODE REVIEW

**Review by tkurki — CHANGES_REQUESTED** [review]
So backoff increases without limit? I don't think that is sensible - if you leave your source turned off for days but the receiving client (for example at the server) on and retrying the delay grows too long. Add `maxRetryInterval`?

I don't think 10 retries is sensible either - in what scenario would that be optimal? I would retry either without limit or once by default, any other number is arbitrary to me.

**Comment by fabdrol** [comment]
@tkurki the max back-off time is limited by the max retries; but I see your point. If someone were to set it to, say `Infinity`, after some time the time between retries would get very big. What would you suggest to be a sensible default for the `maximum time between retries`?

Regarding limiting the retries: that number of 10 is based on my own use case. I have a number of clients whose network connection is sometimes flaky. I don't want them to try and connect indefinitely, but I do want them to have enough retries in order to get the connection. I'm not against setting the default to `Infinity`, but I can imagine others have this problem too if connecting wirelessly.

**Comment by tkurki** [comment]
What exactly is the problem with infinite retries? 

Max delay in the order of seconds to tens of seconds will eventually connect and not cause excessive load or network traffic. 

Also in the case where the source server is not yet up / reachable when the client starts.

**Comment by fabdrol** [comment]
@tkurki nothing, as I said I'm not against setting that as the default. I can set my instance of client to 10 when required ;).

**Comment by fabdrol** [comment]
@tkurki see new changes

**Comment by fabdrol** [comment]
@tkurki can we merge this?

**Review by tkurki — CHANGES_REQUESTED** [review]
The retry mechanism seems to work, the only problem that I found is that calling `disconnect` on  a client that is not connected throws 
```
(node:13413) UnhandledPromiseRejectionWarning: Error: Not connected to WebSocket
    at Connection.send (/Users/tjk/git-workspace/signalk/signalk-js-client/dist/lib/connection.js:354:29)
    at Connection.unsubscribe (/Users/tjk/git-workspace/signalk/signalk-js-client/dist/lib/connection.js:332:10)
    at Client.disconnect (/Users/tjk/git-workspace/signalk/signalk-js-client/dist/lib/client.js:271:23)
```

Disconnect is now more important than before, because afai can tell that is the way to stop the reconnects.

README does not document the events that client is emitting during the lifecycle of a ws connection, so a user of this lib needs to dig into the source to figure out how to make use of the reconnect mechanism. This applies also to `fetchReady`. 

If `connect` does not succeed on the first try the promise fails, so it can not be used to wait for a successful connection. A ws connection may also be disconnected and reconnected for example when the other end is rebooted, so there should be some guidance to use the events to manage the connection state, not the Promise.

**Comment by fabdrol** [comment]
Good catch @tkurki. Added a test for that, and fixed.

**Pull request merged**
