### PR TITLE
Refactor client to match current specification on how subscriptions work

### PR DESCRIPTION
**Pull request by fabdrol**
This PR is the result of an effort to refactor the client to handle subscriptions differently. This involves a significant change, hence it includes a minor version bump (to 2.1.0). 

This PR solves (and in some cases, avoids) issues: 
- https://github.com/SignalK/signalk-js-client/issues/75
- https://github.com/SignalK/signalk-js-client/issues/73
- https://github.com/SignalK/signalk-js-client/issues/72
- https://github.com/SignalK/signalk-js-client/issues/71

The PR additionally supersedes: https://github.com/SignalK/signalk-js-client/pull/74

It also resolves an earlier reported issue and PR that mentioned iKommunicate compatibility.

### CODE REVIEW

**Comment by fabdrol** [comment]
@tkurki there will be some code changes here and there that are not strictly related to this feature (which I know you dislike), which was unavoidable in this case due to the size of the change. So please review this based on the actual issue it solves first; unrelated stuff can be discussed when we are happy with the resolution of the issue at hand.

**Comment by tkurki** [comment]
Oh, did you mean this instead of #74? If not what did you mean with _supercedes_?

**Comment by fabdrol** [comment]
@tkurki with this PR the other one wasn't required anymore, since this one refactors the entire stream API. That said, I will need to come up with a solution for that - see my response to your comment on the issue for this.

**Comment by fabdrol** [comment]
@tkurki besides the name discussion, this now supports the various other things discussed. Changes:

- Remove `legacy` behaviour (can be set by setting the param to `null`) and `subscription` behaviour as a separate option
- Make `none` subscription the default
- Implement `subscribe()` and `unsubscribe()` methods
- Change config parameter `subscription` to `subscriptions`, which accepts an array of subscription commands that are send to the server right after the connection's been established

**Comment by tkurki** [comment]
Another user having trouble with iKommunicate, we need to get that issue fixed.

Let's go with your naming to move forward.

I have not reviewed the code, maybe we should next do the changes in server against this branch and make sure things work? 

I don't think I have the any proper time for this for some days to come.

**Pull request merged**
