### PR TITLE
Revert bonjour

### PR DESCRIPTION
**Pull request by tkurki**
This pull request will revert the switch from mdns to bonjour in PR #66  and publish a new patch version 2.1.2, because this changes the API of the client and should have been a major version.

Once this is merged and published we should deprectate version 2.1.1 and 2.1.0.

@cmotelet any thoughts?

### CODE REVIEW

**Comment by fabdrol** [comment]
@tkurki is this just because a minor/major version change? Because I'd rather not go backwards.

**Comment by tkurki** [comment]
The public interface of the client changed in 2.1.1 with a breaking change because the client expects now a Bonjour, not and Mdns. That was a breaking change. How do you propose to resolve that? My proposal is to revert the change and publish a new major version.

**Comment by fabdrol** [comment]
@tkurki I'd rather not, it seems like a faff. How about implementing a check of the provided library, and offer support for both mdns and bonjour?

**Comment by tkurki** [comment]
I broke it when I merged the PR, so I am trying to first fix that with a simple revert - most likely won't have the time for implementing and testing dual support. Can you do that?

**Comment by fabdrol** [comment]
@tkurki yep, I can take that on.

**Comment by fabdrol** [comment]
@tkurki see: https://github.com/SignalK/signalk-js-client/pull/89

**Review by fabdrol — COMMENTED** [review]
superseded by https://github.com/SignalK/signalk-js-client/pull/89

**Pull request closed without merging**
